import { Letter } from "./types";

export const INITIAL_LETTERS: Letter[] = [
  {
    id: "star-1",
    recipient: "To Mom in Room 402",
    content: "It has been three years since you closed your eyes. I finally bought the apartment you prayed for. The kitchen has the wide window overlooking the trees just like you imagined. I sat on the floor today and cried because you are not here to boil the tea. I hope whatever sky you are looking at now is warm.",
    category: "grief",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    resonantLetterId: "star-6",
    resonanceNote: "Connected by an invisible thread across 9,500 km: Two souls carrying unspoken grief for a departed parent.",
    whispers: [
      {
        id: "w-1",
        text: "She saw you get the keys. A mother's soul never leaves her child's kitchen.",
        createdAt: "Founding star",
        locationName: "Solas Haven"
      },
      {
        id: "w-2",
        text: "Brew the tea anyway. Leave a cup on the counter for her.",
        createdAt: "Founding star",
        locationName: "Solas Haven"
      }
    ],
    x: -320,
    y: -210,
    size: 4.2,
    color: "#38bdf8",
    glowColor: "rgba(56, 189, 248, 0.7)",
    pulseSpeed: 1.8,
    pulsePhase: 0.2
  },
  {
    id: "star-2",
    recipient: "To My Unborn Daughter (Sophia)",
    content: "We had already bought your yellow knitted socks. Your mother held your ultrasound picture against her chest for three months without letting go. I never heard your cry, but I swear on my life, you were loved for every single second you breathed beneath her heart.",
    category: "grief",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    whispers: [
      {
        id: "w-3",
        text: "Little Sophia is cradled in peace. You are wonderful parents.",
        createdAt: "Founding star",
        locationName: "Solas Haven"
      }
    ],
    x: 410,
    y: -180,
    size: 4.8,
    color: "#38bdf8",
    glowColor: "rgba(56, 189, 248, 0.8)",
    pulseSpeed: 1.4,
    pulsePhase: 1.1
  },
  {
    id: "star-3",
    recipient: "To The Boy At The Bus Stop (2018)",
    content: "We shared an umbrella for twenty-two minutes during an autumn storm. You had wet eyelashes and ink stains on your fingers. I never asked for your name because I thought we would meet again. Six years later, whenever rain hits the asphalt, my heart still looks for your blue jacket.",
    category: "love",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    resonantLetterId: "star-12",
    resonanceNote: "Resonant Orbit: Two lovers across opposite hemispheres remembering the one who slipped away.",
    whispers: [
      {
        id: "w-4",
        text: "Some people are only meant to be rain showers, not the whole season.",
        createdAt: "Founding star",
        locationName: "Solas Haven"
      }
    ],
    x: -180,
    y: 280,
    size: 3.5,
    color: "#f43f5e",
    glowColor: "rgba(244, 63, 94, 0.7)",
    pulseSpeed: 2.1,
    pulsePhase: 2.3
  },
  {
    id: "star-4",
    recipient: "To God, in the 3:00 AM silence",
    content: "I don't know if my whisper makes it past the ceiling of this small rented room. But tonight, I have no pride left. The world is too fast and my chest feels so fragile. Please just give me the strength to wake up tomorrow and believe that goodness still exists in me.",
    category: "prayer",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    resonantLetterId: "star-13",
    resonanceNote: "Synchronous Midnight Whispers: Shared prayers in the quiet void seeking light and endurance.",
    whispers: [
      {
        id: "w-5",
        text: "He hears the whisper in the dark room clearer than the shouting in the streets. Hold on.",
        createdAt: "Founding star",
        locationName: "Solas Haven"
      }
    ],
    x: 120,
    y: -340,
    size: 5.0,
    color: "#fbbf24",
    glowColor: "rgba(251, 191, 36, 0.9)",
    pulseSpeed: 1.2,
    pulsePhase: 0.8
  },
  {
    id: "star-5",
    recipient: "To My Younger Self at 16",
    content: "Put down the scissors. I know you think nobody sees the shame burning in your throat. I am writing to you from 12 years in the future: you survived the storm. You learned how to laugh from your belly again. You found people who love your quietness. Forgive yourself for not knowing how to survive.",
    category: "forgiveness",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    whispers: [
      {
        id: "w-6",
        text: "Thank you for surviving. Someone needed to read this tonight.",
        createdAt: "Founding star",
        locationName: "Solas Haven"
      }
    ],
    x: 310,
    y: 240,
    size: 4.6,
    color: "#34d399",
    glowColor: "rgba(52, 211, 153, 0.8)",
    pulseSpeed: 1.6,
    pulsePhase: 3.1
  },
  {
    id: "star-6",
    recipient: "To Dad",
    content: "I wore your old watch to my graduation. When they called my name, I reached for my wrist and touched the scratched glass where your thumb always rested. I wish you had lived to see that your son made it out of the factory town.",
    category: "grief",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    resonantLetterId: "star-1",
    resonanceNote: "Connected by an invisible thread across 9,500 km: Two souls carrying unspoken grief for a departed parent.",
    whispers: [],
    x: -450,
    y: 80,
    size: 3.9,
    color: "#38bdf8",
    glowColor: "rgba(56, 189, 248, 0.6)",
    pulseSpeed: 1.9,
    pulsePhase: 1.5
  },
  {
    id: "star-7",
    recipient: "To You, Who I Broke",
    content: "I was too young and full of poisoned fear. You gave me tenderness, and I responded with silence and cruelty because I didn't think I deserved to be held. You are married now and I pray every night that he treats your delicate heart like the sanctuary it is.",
    category: "forgiveness",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    whispers: [],
    x: -240,
    y: -420,
    size: 3.8,
    color: "#34d399",
    glowColor: "rgba(52, 211, 153, 0.7)",
    pulseSpeed: 2.0,
    pulsePhase: 0.5
  },
  {
    id: "star-8",
    recipient: "To The Stranger Who Didn't Let Me Jump",
    content: "You were walking your golden retriever on the bridge in December 2021. You didn't give a speech. You just offered me half of your warm pretzel and asked if I wanted to pet your dog. You saved a human life without ever knowing it. Bless you wherever you are walking today.",
    category: "prayer",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    whispers: [],
    x: -80,
    y: 450,
    size: 5.2,
    color: "#fbbf24",
    glowColor: "rgba(251, 191, 36, 0.85)",
    pulseSpeed: 1.3,
    pulsePhase: 2.7
  },
  {
    id: "star-9",
    recipient: "To My Best Friend Who Faded Away",
    content: "We promised we would be the crazy grandmas drinking coffee on a porch in Portugal. Life didn't have a giant fight—just busy calendars, unanswered texts, and quiet drift. I still celebrate your birthday every March 14th with chocolate ice cream. I hope your dreams came true.",
    category: "unsent",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    whispers: [],
    x: 520,
    y: 30,
    size: 3.6,
    color: "#c084fc",
    glowColor: "rgba(192, 132, 252, 0.7)",
    pulseSpeed: 1.7,
    pulsePhase: 1.9
  },
  {
    id: "star-10",
    recipient: "To The Stars",
    content: "I am leaving my burden here. I carried the guilt of someone else's mistake for twenty years. Tonight I am laying it down on this altar of starlight. I am free.",
    category: "unsent",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    whispers: [],
    x: 210,
    y: -140,
    size: 4.1,
    color: "#c084fc",
    glowColor: "rgba(192, 132, 252, 0.75)",
    pulseSpeed: 2.2,
    pulsePhase: 0.1
  },
  {
    id: "star-11",
    recipient: "To Grandma's Garden",
    content: "Your jasmine still blooms every July. The scent fills the entire alley. Whenever the wind blows the white petals across my feet, I feel your wrinkly hands resting on my forehead.",
    category: "grief",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    whispers: [],
    x: -550,
    y: -300,
    size: 3.4,
    color: "#38bdf8",
    glowColor: "rgba(56, 189, 248, 0.6)",
    pulseSpeed: 1.5,
    pulsePhase: 3.4
  },
  {
    id: "star-12",
    recipient: "To The One I Let Slip Away",
    content: "If love was enough, we would be old together right now. But timing, borders, and timing again tore our hands apart. In another dimension, another version of us is dancing in that kitchen listening to vinyl records.",
    category: "love",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    resonantLetterId: "star-3",
    resonanceNote: "Resonant Orbit: Two lovers across opposite hemispheres remembering the one who slipped away.",
    whispers: [],
    x: 450,
    y: -390,
    size: 4.4,
    color: "#f43f5e",
    glowColor: "rgba(244, 63, 94, 0.8)",
    pulseSpeed: 1.7,
    pulsePhase: 1.2
  },
  {
    id: "star-13",
    recipient: "To Anyone Feeling Invisible Tonight",
    content: "If no one has told you today: your existence on this earth is not a mistake. The heavy thoughts lying to you in the dark will not last. Breathe slowly. Drink water. The morning will bring mercy.",
    category: "prayer",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    resonantLetterId: "star-4",
    resonanceNote: "Synchronous Midnight Whispers: Shared prayers in the quiet void seeking light and endurance.",
    whispers: [],
    x: 0,
    y: 0,
    size: 5.5,
    color: "#fbbf24",
    glowColor: "rgba(251, 191, 36, 1.0)",
    pulseSpeed: 1.0,
    pulsePhase: 0
  },
  {
    id: "star-tc-1",
    recipient: "To My Future Self (On My 30th Birthday)",
    content: "This time capsule is sealed in cosmic starlight. If you are reading this on December 31st, I hope you finally learned to be kind to yourself. I hope you forgave the mistakes of your twenties, and I hope you are still watching the winter rain with wonder.",
    category: "unsent",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    whispers: [],
    isTimeCapsule: true,
    igniteDate: "2026-12-31",
    x: -290,
    y: 380,
    size: 5.8,
    color: "#38bdf8",
    glowColor: "rgba(56, 189, 248, 0.9)",
    pulseSpeed: 0.8,
    pulsePhase: 1.4
  },
  {
    id: "star-tc-2",
    recipient: "To The Day We Finally Meet Again",
    content: "A promise sealed across time. We agreed not to speak for one year so both of our hearts could heal in silence. When this star ignites next summer, I will know that peace has finally replaced the ache.",
    category: "love",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    whispers: [],
    isTimeCapsule: true,
    igniteDate: "2027-06-21",
    x: 350,
    y: -310,
    size: 5.6,
    color: "#f43f5e",
    glowColor: "rgba(244, 63, 94, 0.9)",
    pulseSpeed: 0.9,
    pulsePhase: 2.1
  },
  {
    id: "star-14",
    recipient: "To Everyone Who Thinks I Have It All Together",
    content: "I tell everyone I am doing fine, that the divorce didn't break me, and that I love my quiet new apartment. The truth is, I haven't cooked a warm meal in months. I leave the hallway light on because the silence at 2 AM is so heavy it makes my chest ache. I just want someone to hold me and tell me I am not a failure.",
    category: "confession",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    resonantLetterId: "star-15",
    resonanceNote: "Two souls across continents admitting their hidden exhaustion and seeking gentleness.",
    whispers: [
      {
        id: "w-c1",
        text: "You are surviving something terrifying. You are not a failure for feeling tired.",
        createdAt: "Founding star",
        locationName: "Solas Haven"
      }
    ],
    x: 180,
    y: 320,
    size: 4.5,
    color: "#e879f9",
    glowColor: "rgba(232, 121, 249, 0.75)",
    pulseSpeed: 1.6,
    pulsePhase: 0.7
  },
  {
    id: "star-15",
    recipient: "To My Younger Sister (Maya)",
    content: "Ten years ago, I took the fifty dollars from your birthday card to pay for my bus ticket when I ran away. You cried and thought you had dropped it in the park grass. I've sent you expensive gifts every birthday since, but the guilt still eats at me every time you smile. I'm leaving this truth here because I'm still learning how to be brave.",
    category: "confession",
    createdAt: "Founding star",
    locationName: "Solas Haven",
    lightCount: 0,
    resonantLetterId: "star-14",
    whispers: [
      {
        id: "w-c2",
        text: "Tell her one day. Love forgives the frightened things we did when we were young.",
        createdAt: "Founding star",
        locationName: "Solas Haven"
      }
    ],
    x: -380,
    y: -90,
    size: 4.8,
    color: "#e879f9",
    glowColor: "rgba(232, 121, 249, 0.75)",
    pulseSpeed: 1.4,
    pulsePhase: 1.1
  }
];